<?php
$pfHelper = Mage::helper("payfort/data");
?>

<?php if($pfHelper->isMerchantPageMethod()):?>
<div class="pf-iframe-background" id="div-pf-iframe" style="display:none">
    <div class="pf-iframe-container">
        <span class="pf-close-container">
            <i class="fa fa-times-circle pf-iframe-close" onclick="payfortFortMerchantPage.closePopup()"></i>
        </span>
        <i class="fa fa-spinner fa-spin pf-iframe-spin"></i>
        <div class="pf-iframe" id="pf_iframe_content"></div>
    </div>
</div>
<?php endif; ?>


